
server:
    port: 2025

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/exceptionhandler
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true